/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class Confirmar_Pagamento {
    global Case c {
        get;
        set;
    }
    global Boolean criarCaso {
        get;
        set;
    }
    global Boolean detail {
        get;
        set;
    }
    global String emailCliente {
        get;
        set;
    }
    global Boolean existeErro {
        get;
        set;
    }
    global String nomeCliente {
        get;
        set;
    }
    global String phoneCliente {
        get;
        set;
    }
    global Boolean retentar {
        get;
        set;
    }
    global String xmlTeste;
    global Confirmar_Pagamento() {

    }
    global void criaCaso(String erro) {

    }
    global void getMessages() {

    }
    global void insereCaso() {

    }
    global void pagNOK(String erro, Boolean nAut) {

    }
    global void pagOK() {

    }
    global System.PageReference retornar() {
        return null;
    }
}
