@isTest
public class wRAPPERUTILS_test {

    static testMethod void unitTest_1(){
        test.startTest();
        wrapperUtils.addressWrapper address = new wrapperUtils.addressWrapper();
        wrapperUtils.upsWrapper ups = new wrapperUtils.upsWrapper();
        wrapperutils.wrapperProductInfo info = new wrapperutils.wrapperProductInfo();
        wrapperutils.wrapperProductDetails details = new wrapperutils.wrapperProductDetails();
        test.stopTest();
    }
}