
/*
*This is the class
*/
public class DivZero {

	/* comments on erry thang */
  private final Integer newGuy;

  /*
	*This is the constructor
	*/
  public DivZero(Integer value) {
		newGuy = value;
		blahBlah();
		value = 4;
		newGuy = newGuy;
				newGuy = newGuy;
						newGuy = newGuy;
								newGuy = newGuy;
										newGuy = newGuy;
												newGuy = newGuy;
														newGuy = newGuy;
																newGuy = newGuy;
																		newGuy = newGuy;
	}

	private static void empty() {}



  private static Integer blahBlah(Integer value) {
		return value + 1;
	}

/*
* comment
*/
  public void blah(Integer newInt) {
    
		final Integer old = newguy + newInt;
		bar(old);	
		unreach('blah');
		newInt = 3;
	
		
  }

	/*
	* Comment
	*/
	public static void bar(String param) {
		try {
			doStuff();
		} catch (IOException e) {
			blah();
		}
	}
//coment \ u \n 

// comment \ca for TST3 as domain data was loaded with \ca and \ us
 private static void unreach(String newParam) {


 }
	//change
	
}



