public class reportWrapper
{
    public Product_Refunds__c Refund_Object{get;set;}
    public Opportunity opp{get;set;}
    public Decimal dTotal{get;set;}
    public Boolean isAutoRenew{get;set;}
    public String strShipTo{get;set;}
    public String strShippingInfo{get;set;}
    public ChargentSFA__Transaction__c payment{get;set;}
    public Decimal AFREE4999Amount {get;set;}
    public Decimal CBR4000Amount {get;set;}
    public Decimal CBR2A4000Amount {get;set;}
    public Decimal CBREL4000Amount {get;set;}
    public Decimal CBRHB4030Amount {get;set;}
    public Decimal CBRHI4030Amount {get;set;}
    public Decimal CBRNM4000Amount {get;set;}
    public Decimal CHMT14070Amount {get;set;}
    public Decimal CMCNY4070Amount {get;set;}
    public Decimal CMCNY4060Amount {get;set;}
    public Decimal CNY134060Amount {get;set;}
    public Decimal CNY134070Amount {get;set;}
    public Decimal CRF4060Amount {get;set;}
    public Decimal CRF4070Amount {get;set;}
    public Decimal CRFA4070Amount {get;set;}
    public Decimal CRFA4060Amount {get;set;}
    public Decimal CRT4070Amount {get;set;}
    public Decimal CRT4060Amount {get;set;}
    public Decimal ENC4010Amount {get;set;}
    public Decimal ENC4020Amount {get;set;}
    public Decimal ENCBN4030Amount {get;set;}
    public Decimal ENCCP4030Amount {get;set;}
    public Decimal ENCE4001Amount {get;set;}
    public Decimal ENCE4002Amount {get;set;}
    public Decimal ENCL4001Amount {get;set;}
    public Decimal ENCL4002Amount {get;set;}
    public Decimal ENCS4001Amount {get;set;}
    public Decimal ENCS4002Amount {get;set;}
    public Decimal ENCSW4001Amount {get;set;}
    public Decimal ENCSW4002Amount {get;set;}
    public Decimal ERD4110Amount {get;set;}
    public Decimal FBRHB4030Amount {get;set;}
    public Decimal FBRNM4000Amount {get;set;}
    public Decimal FCBR4000Amount {get;set;}
    public Decimal FRM14020Amount {get;set;}
    public Decimal FRM14010Amount {get;set;}
    public Decimal FRM1E4001Amount {get;set;}
    public Decimal FRM1E4002Amount {get;set;}
    public Decimal FRM1H4030Amount {get;set;}
    public Decimal FRM1L4001Amount {get;set;}
    public Decimal FRM1L4002Amount {get;set;}
    public Decimal FRM1N4030Amount {get;set;}
    public Decimal FRM1S4002Amount {get;set;}
    public Decimal FRM1S4001Amount {get;set;}
    public Decimal FRM2E4002Amount {get;set;}
    public Decimal FRM2E4001Amount {get;set;}
    public Decimal FRM2H4030Amount {get;set;}
    public Decimal FRM2L4002Amount {get;set;}
    public Decimal FRM2L4001Amount {get;set;}
    public Decimal FRM2N4030Amount {get;set;}
    public Decimal FRM2S4001Amount {get;set;}
    public Decimal FRM2S4002Amount {get;set;}
    public Decimal FRMCN4030Amount {get;set;}
    public Decimal FRMCP4030Amount {get;set;}
    public Decimal GL0051GL0051Amount {get;set;}
    public Decimal GL0050GL0050Amount {get;set;}
    public Decimal GRPW4102Amount {get;set;}
    public Decimal GRPW4092Amount {get;set;}
    public Decimal GRPW4104Amount {get;set;}
    public Decimal GRPW4091Amount {get;set;}
    public Decimal IFC124000Amount {get;set;}
    public Decimal IND14060Amount {get;set;}
    public Decimal MEA4000Amount {get;set;}
    public Decimal MEMC4040Amount {get;set;}
    public Decimal MEMF4040Amount {get;set;}
    public Decimal MEMI4040Amount {get;set;}
    public Decimal MEMS4040Amount {get;set;}
    public Decimal MEMW2007Amount {get;set;}
    public Decimal MISC4999Amount {get;set;}
    public Decimal PRFEE6110Amount {get;set;}
    public Decimal SHIP4999Amount {get;set;}
    public Decimal SLSTX2819Amount {get;set;}
    public Decimal TCEM4080Amount {get;set;}
    public Decimal WEBN4070Amount {get;set;}
    public Decimal WEBN4060Amount {get;set;}
    
    public Decimal FRM1RefundAmt {get;set;}
    public Decimal FRM1ERefundAmt {get;set;}
    public Decimal FRM1HRefundAmt {get;set;}
    public Decimal FRM1LRefundAmt {get;set;}
    public Decimal FRM2ERefundAmt {get;set;}
    public Decimal FRM2HRefundAmt {get;set;}
    public Decimal FRM2LRefundAmt {get;set;}
    public Decimal MEMFRefundAmt {get;set;}
    public Decimal MEMIRefundAmt {get;set;}
    public Decimal SHIPRefundAmt {get;set;}
    public Decimal SLSTXRefundAmt {get;set;}

    public Decimal FRM1ShipAmt {get;set;}
    public Decimal FRM2ShipAmt {get;set;}
    public Decimal ERPShipAmt {get;set;}
    public Decimal FBRShipAmt {get;set;}
    public Decimal ICBRRShipAmt {get;set;}
    
    public Decimal TaxableAmount{get;set;}
}