Global class SGLedOpptyGetResponse {    
    public string LeadID;
    public string accountId;
    public String opportunityId;
    public string contactId;
    public String contractId;
	public string SFDCAccountID;
    public String CustomerFirstName;
    public String CustomerLastName;
    public String Company;
    public String Phone;    
    public String Email;
    public String Street;
    public String City;
    public String State;
    public String PostalCode;
    public String Country;
    public String RepFirstName;
    public String RepLastName;
}