public class Trigger_Controller{
    public static boolean Oportunidade_Controller {
        get{
            if(Oportunidade_Controller == null) return true;
            else return Oportunidade_Controller;
        }
        
        set;
    }
    
    public static boolean Oli_Controller{
        get{
            if(Oli_Controller== null) return true;
            else return Oli_Controller;
        }
        
        set;
    }
    
    public static boolean Accoutn_controller{
        get{
            if(Accoutn_controller == null) return true;
            else return Accoutn_controller;
        }
        
        set;
    }
    
    public static boolean Membros_campanha_controller{
        get{
            if(Membros_campanha_controller == null) return true;
            else return Membros_campanha_controller;
        }
        
        set;
    }
    
    
    public static boolean Lead_trigger{
        get{
            if(Lead_trigger== null) return true;
            else return Lead_trigger;
        }
        
        set;
    }
}