/**
 * Class: APTPS_DaikinConstants
 * Description : It holds constants used in classes, pages etc.
 * Author : @Apttus
 **/
public class APTPS_DaikinConstants {

    public static String APTPS_Quote_RT_Latin_America = 'Latin America Proposal';
    public static String APTPS_Quote_RT_North_America = 'North America Proposal';
    
    public static String APTPS_QuoteLineItem_RT_Latin_America = 'Latin America Proposal';
    public static String APTPS_QuoteLineItem_RT_North_America = 'North America Proposal';

}